name: Laravel

on: [push]

jobs:
  laravel-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Build image
      run: docker build -t inplayer/spi-access-sync .
    - name: Login to ECR
      uses: jwalton/gh-ecr-login@v1.0.0
      with:
        access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: eu-central-1
    - name: Push to ECR
      run: |
          docker tag inplayer/spi-access-sync ${{ steps.ecr.outputs.account }}.dkr.ecr.eu-central-1.amazonaws.com/spi-access-sync:build-${{ github.sha }}
          docker push ${{ steps.ecr.outputs.account }}.dkr.ecr.eu-central-1.amazonaws.com/spi-access-sync:build-${{ github.sha }} 
